site:
  title: Tandem Methodology (preview)
  start_page: tandem::index.adoc
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
    kroki-default-format: svg
output:
  dir: docs/build/site
runtime:
  log:
    failure_level: warn
